version: '3.8'

services:
  app:
    build:
      context: ./chat-webapp
      target: runner
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    user: "1001:1001" 
    command: node server.js
    restart: unless-stopped
